import LoginContent from '../../../components/login/LoginContent';

export const metadata = {
  title: 'Digiboard - Login Page',
  description: 'Generated by create next app',
};

export default function LoginPage() {
  return <LoginContent />;
}
